import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import Link from 'next/link'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
          {' '}
          <nav className="py-3 px-4 flex items-center gap-4 justify-between shadow-md sticky top-0">
            <div id="Logo" className="flex gap-3 items-center">
              <div className="rounded-full bg-accent size-8"></div>
              <p className="uppercase font-bold">Website Title</p>
            </div>
            <div id="nav-links" className="flex gap-4 items-center">
              <Link href="/" className="hover:underline hover:text-foreground/80 transition-all">
                Home
              </Link>
              <Link href="/about" className="hover:underline hover:text-foreground/80 transition-all">
                About
              </Link>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </nav>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
